version: '3.8'
<<<<<<< HEAD
services:
  spark:
    build: .
    container_name: pyspark_dev
=======

services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark-dev
>>>>>>> fix/devcontainer-setup
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/app
    environment:
      - PYSPARK_PYTHON=python3
<<<<<<< HEAD
      - PYSPARK_DRIVER_PYTHON=python3
      - SPARK_MASTER=local[*]
      - PYTHONPATH=/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip
    working_dir: /app
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
      --NotebookApp.token='' --NotebookApp.password=''
      --NotebookApp.base_url=/ --NotebookApp.allow_origin='*' &
      /bin/bash"
=======
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''
      - SPARK_MASTER=local[*]
    working_dir: /app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
>>>>>>> fix/devcontainer-setup
