version: '3.8'

services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark-dev
    ports:
      - "8888:8888"  # Jupyter
      - "4040:4040"  # Spark UI
    volumes:
      - .:/app
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''
      - SPARK_MASTER=local[*]
    working_dir: /app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
